jq

diff --git a/.github/workflows/s3-sync-action.yml b/.github/workflows/s3-sync-action.yml
--- a/.github/workflows/s3-sync-action.yml
+++ b/.github/workflows/s3-sync-action.yml
@@ -49,7 +49,8 @@ jobs:
       - name: "Deploy CloudFormation Stack"
         run: |
             stacklist=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --output text)
-            echo "stacklist is $stacklist"
+            echo "$stacklist" | jq -r '.[]' | grep -w "bootstrap-stack" || echo "bootstrap-stack not found"
+
             # aws cloudformation create-stack \
             #     --template-file main.yaml \
             #     --stack-name bootstrap-stack \
